// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/gamezop.proto

package gamezoppb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GamezopRequest struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamezopRequest) Reset()         { *m = GamezopRequest{} }
func (m *GamezopRequest) String() string { return proto.CompactTextString(m) }
func (*GamezopRequest) ProtoMessage()    {}
func (*GamezopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9bddf403ab2b95, []int{0}
}

func (m *GamezopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamezopRequest.Unmarshal(m, b)
}
func (m *GamezopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamezopRequest.Marshal(b, m, deterministic)
}
func (m *GamezopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamezopRequest.Merge(m, src)
}
func (m *GamezopRequest) XXX_Size() int {
	return xxx_messageInfo_GamezopRequest.Size(m)
}
func (m *GamezopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GamezopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GamezopRequest proto.InternalMessageInfo

func (m *GamezopRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *GamezopRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GamezopResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamezopResponse) Reset()         { *m = GamezopResponse{} }
func (m *GamezopResponse) String() string { return proto.CompactTextString(m) }
func (*GamezopResponse) ProtoMessage()    {}
func (*GamezopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd9bddf403ab2b95, []int{1}
}

func (m *GamezopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamezopResponse.Unmarshal(m, b)
}
func (m *GamezopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamezopResponse.Marshal(b, m, deterministic)
}
func (m *GamezopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamezopResponse.Merge(m, src)
}
func (m *GamezopResponse) XXX_Size() int {
	return xxx_messageInfo_GamezopResponse.Size(m)
}
func (m *GamezopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GamezopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GamezopResponse proto.InternalMessageInfo

func (m *GamezopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GamezopResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GamezopResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GamezopRequest)(nil), "gamezoppb.GamezopRequest")
	proto.RegisterType((*GamezopResponse)(nil), "gamezoppb.GamezopResponse")
}

func init() { proto.RegisterFile("protos/gamezop.proto", fileDescriptor_fd9bddf403ab2b95) }

var fileDescriptor_fd9bddf403ab2b95 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xb5, 0x4a, 0x47, 0xb0, 0xb2, 0x54, 0x88, 0x51, 0x50, 0xf2, 0x24, 0x3e, 0x24,
	0xa8, 0x6f, 0x5e, 0xa0, 0x6f, 0x22, 0xe9, 0x01, 0x64, 0xda, 0x0e, 0x21, 0xb0, 0xbb, 0xb3, 0x66,
	0xd7, 0x4a, 0x7d, 0xf4, 0x0a, 0x1e, 0xcd, 0x2b, 0x78, 0x10, 0xe9, 0xac, 0x1b, 0x10, 0x7c, 0x9b,
	0xff, 0x9b, 0x9f, 0x9f, 0x99, 0x1f, 0x66, 0xae, 0xe7, 0xc0, 0xbe, 0x6e, 0xd1, 0xd0, 0x3b, 0xbb,
	0x4a, 0xa4, 0x9a, 0xfc, 0x4a, 0xb7, 0x2c, 0x2e, 0x5a, 0xe6, 0x56, 0x53, 0x8d, 0xae, 0xab, 0xd1,
	0x5a, 0x0e, 0x18, 0x3a, 0xb6, 0x3e, 0x1a, 0xcb, 0x39, 0x1c, 0xcf, 0xa3, 0xb5, 0xa1, 0x97, 0x57,
	0xf2, 0x41, 0x5d, 0xc2, 0x91, 0xd3, 0xb8, 0xa5, 0xfe, 0xd9, 0xa2, 0xa1, 0x3c, 0xbb, 0xca, 0xae,
	0x27, 0x0d, 0x44, 0xf4, 0x88, 0x86, 0xd4, 0x0c, 0xc6, 0x64, 0xb0, 0xd3, 0xf9, 0x48, 0x56, 0x51,
	0x94, 0x0b, 0x98, 0x0e, 0x41, 0xde, 0xb1, 0xf5, 0xa4, 0x72, 0x38, 0x34, 0xe4, 0x3d, 0xb6, 0x29,
	0x25, 0x49, 0xa5, 0x60, 0x7f, 0xc5, 0x6b, 0x92, 0x84, 0x71, 0x23, 0xf3, 0x8e, 0xad, 0x31, 0x60,
	0xbe, 0x27, 0x56, 0x99, 0xef, 0xde, 0x86, 0xeb, 0x16, 0xd4, 0x6f, 0xba, 0x15, 0x29, 0x82, 0xe9,
	0x93, 0xc6, 0xed, 0x8e, 0x26, 0x74, 0x56, 0x0d, 0xcf, 0x56, 0x7f, 0x7f, 0x29, 0x8a, 0xff, 0x56,
	0xf1, 0xba, 0xf2, 0xfc, 0xe3, 0xeb, 0xfb, 0x73, 0x74, 0x5a, 0x9e, 0xd4, 0x9b, 0x5b, 0x69, 0x2f,
	0x55, 0xf8, 0x90, 0xdd, 0x2c, 0x0f, 0xa4, 0x9d, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x47, 0x60, 0x3a, 0x5e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GamezopServiceClient is the client API for GamezopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GamezopServiceClient interface {
	PlayGameService(ctx context.Context, in *GamezopRequest, opts ...grpc.CallOption) (*GamezopResponse, error)
}

type gamezopServiceClient struct {
	cc *grpc.ClientConn
}

func NewGamezopServiceClient(cc *grpc.ClientConn) GamezopServiceClient {
	return &gamezopServiceClient{cc}
}

func (c *gamezopServiceClient) PlayGameService(ctx context.Context, in *GamezopRequest, opts ...grpc.CallOption) (*GamezopResponse, error) {
	out := new(GamezopResponse)
	err := c.cc.Invoke(ctx, "/gamezoppb.GamezopService/PlayGameService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamezopServiceServer is the server API for GamezopService service.
type GamezopServiceServer interface {
	PlayGameService(context.Context, *GamezopRequest) (*GamezopResponse, error)
}

func RegisterGamezopServiceServer(s *grpc.Server, srv GamezopServiceServer) {
	s.RegisterService(&_GamezopService_serviceDesc, srv)
}

func _GamezopService_PlayGameService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GamezopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamezopServiceServer).PlayGameService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gamezoppb.GamezopService/PlayGameService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamezopServiceServer).PlayGameService(ctx, req.(*GamezopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GamezopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gamezoppb.GamezopService",
	HandlerType: (*GamezopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayGameService",
			Handler:    _GamezopService_PlayGameService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/gamezop.proto",
}
